# Numpy

In [ ]:
# Basics

import numpy as np

arr1 = np.array([1, 3, 5, 7, 9])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 3 5 7 9]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = arr1.reshape((1,5))
print(arr2)
print(arr2.shape)

[[1 3 5 7 9]]
(1, 5)


In [6]:
arr3 = arr2.reshape((5, 1))
print(arr3)
print(arr3.shape)

[[1]
 [3]
 [5]
 [7]
 [9]]
(5, 1)


In [7]:
arr4 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])
print(arr4)
print(arr4.shape)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
(2, 5)


In [12]:
arr5 = np.arange(-5, 5, 1)
print(arr5)
arr5 = arr5.reshape((2, 5))
print(arr5)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[[-5 -4 -3 -2 -1]
 [ 0  1  2  3  4]]


In [20]:
zero = np.zeros(5)
print(zero)

one = np.ones(5)
print('\n',one)

iden = np.eye(5)
print('\n',iden)

[0. 0. 0. 0. 0.]

 [1. 1. 1. 1. 1.]

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
print(iden.shape)
print(iden.ndim)
print(iden.size)
print(iden.dtype)
print(iden.itemsize)



(5, 5)
2
25
float64
8


In [22]:
# Vectorized Operations

ar1 = np.array([1, 3, 5, 7, 9])
ar2 = np.array([2, 4, 6, 8, 10])
print(ar1 + ar2)
print(ar1 - ar2)
print(ar1 * ar2)
print(ar1 / ar2)

[ 3  7 11 15 19]
[-1 -1 -1 -1 -1]
[ 2 12 30 56 90]
[0.5        0.75       0.83333333 0.875      0.9       ]


In [27]:
print(np.sqrt(ar2))

print('\n', np.exp(ar1))

print('\n', np.sin(ar1))

print('\n', np.log(ar2))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]

 [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03]

 [ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]

 [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]


In [38]:
ar3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
print(ar3)

print('\n', ar3[0,0], ar3[0][0])

print('\n', ar3[1:,2:])

print('\n', ar3[:,:2])

print('\n', ar3[-1, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 1 1

 [[ 7  8]
 [11 12]]

 [[ 1  2]
 [ 5  6]
 [ 9 10]]

 [ 9 10 11 12]


In [39]:
# Modify array elements

ar3[0, 0] = -1
print(ar3) 

[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
# Statistical Concept - Normalization

dt = np.array([1, 2, 3, 4, 5])
print(dt)

mean = np.mean(dt)
print('\n', mean)

std = np.std(dt)
print('\n', std)

norm_dt = (dt - mean) / std

print('\n', norm_dt)
print('\n',np.mean(norm_dt))
print('\n',np.std(norm_dt))

[1 2 3 4 5]

 3.0

 1.4142135623730951

 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

 0.0

 0.9999999999999999


In [ ]:
dt1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.mean(dt1))
print('\n',np.median(dt1))
print('\n', np.std(dt1))
print('\n', np.var(dt1))

5.5

 5.5

 2.8722813232690143

 8.25


In [48]:
# Logical Operations

print(dt1[dt1 > 4])

print('\n', dt1[(dt1 > 5) & (dt1 < 9)])


[ 5  6  7  8  9 10]

 [6 7 8]
